name: Push to ECR

on:
  push:
    branches:
      - master

env:
  AWS_REGION: "eu-central-1"                   
  ECR_REPOSITORY: nginx

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          echo ${{ env.TEST }}
          echo $ENVIRONMENT_STAGE
          echo ${{ vars.ENVIRONMENT_STAGE }}
