name: Push to ECR

on:
  push:
    branches:
      - main

env:
  AWS_REGION: "eu-central-1"                   
  ECR_REPOSITORY: nginx

jobs:
  actual_deploy:
    strategy:
      fail-fast: true
      matrix:
        target: [ production, testing ]
    uses: ./.github/workflows/deploy.yml
    with:
      target_env: ${{ matrix.target }}
