name: Actual deploy

on:
  push:
    branches:
      - main

jobs:
  actual_deploy:
    strategy:
      fail-fast: true
      matrix:
        target: [ testing, production ]
    name: Deploy
    runs-on: ubuntu-latest
    environment: ${{ matrix.target }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        run: |
          echo ${{ vars.TEST }}

